/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov2heavy_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {20, 1, 1};
static const casadi_int casadi_s5[69] = 
  {20, 12, 0, 0, 0, 0, 7, 14,
  16, 22, 28, 34, 40, 47, 54, 0,
  1, 2, 3, 4, 5, 9, 0, 1,
  2, 3, 5, 9, 10, 0, 1, 0,
  1, 2, 6, 7, 8, 0, 1, 2,
  6, 7, 8, 0, 1, 2, 6, 7,
  8, 3, 7, 8, 9, 10, 11, 3,
  4, 5, 6, 8, 10, 11, 3, 4,
  5, 6, 7, 10, 11};
static const casadi_int casadi_s6[27] = 
  {20, 12, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11};
static const casadi_int casadi_s7[35] = 
  {20, 8, 0, 3, 6, 9, 12, 15,
  18, 21, 24, 6, 7, 11, 6, 7,
  11, 6, 7, 11, 6, 7, 11, 8,
  9, 10, 8, 9, 10, 8, 9, 10,
  8, 9, 10};

/* bluerov2heavy_impl_dae_fun_jac_x_xdot_u:(i0[12],i1[12],i2[8],i3[8],i4[],i5[0])->(o0[20],o1[20x12,54nz],o2[20x12,12nz],o3[20x8,24nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][4] : 0;
  a04=cos(a03);
  a05=(a02*a04);
  a06=arg[0]? arg[0][6] : 0;
  a07=(a05*a06);
  a03=sin(a03);
  a08=(a02*a03);
  a09=arg[0]? arg[0][3] : 0;
  a10=sin(a09);
  a11=(a08*a10);
  a01=sin(a01);
  a09=cos(a09);
  a12=(a01*a09);
  a11=(a11-a12);
  a13=arg[0]? arg[0][7] : 0;
  a14=(a11*a13);
  a07=(a07+a14);
  a14=(a01*a10);
  a15=(a02*a09);
  a16=(a15*a03);
  a16=(a14+a16);
  a17=arg[0]? arg[0][8] : 0;
  a18=(a16*a17);
  a07=(a07+a18);
  a00=(a00-a07);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a07=(a01*a04);
  a18=(a07*a06);
  a19=(a10*a03);
  a20=(a19*a01);
  a20=(a15+a20);
  a21=(a20*a13);
  a18=(a18+a21);
  a21=(a03*a01);
  a22=(a21*a09);
  a23=(a02*a10);
  a22=(a22-a23);
  a24=(a22*a17);
  a18=(a18+a24);
  a00=(a00-a18);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a18=(a04*a10);
  a24=(a18*a13);
  a25=(a03*a06);
  a24=(a24-a25);
  a25=(a04*a09);
  a26=(a25*a17);
  a24=(a24+a26);
  a00=(a00-a24);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a24=arg[0]? arg[0][9] : 0;
  a26=(a19/a04);
  a27=arg[0]? arg[0][10] : 0;
  a28=(a26*a27);
  a28=(a24+a28);
  a29=(a09*a03);
  a30=(a29/a04);
  a31=arg[0]? arg[0][11] : 0;
  a32=(a30*a31);
  a28=(a28+a32);
  a00=(a00-a28);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a28=(a09*a27);
  a32=(a10*a31);
  a28=(a28-a32);
  a00=(a00-a28);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a28=(a10/a04);
  a32=(a28*a27);
  a33=(a09/a04);
  a34=(a33*a31);
  a32=(a32+a34);
  a00=(a00-a32);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a32=4.3917435221783048e-02;
  a34=7.0699999999999996e-01;
  a35=arg[2]? arg[2][0] : 0;
  a36=(a34*a35);
  a37=arg[2]? arg[2][1] : 0;
  a38=(a34*a37);
  a38=(a36+a38);
  a39=-7.0699999999999996e-01;
  a40=arg[2]? arg[2][2] : 0;
  a41=(a39*a40);
  a38=(a38+a41);
  a41=arg[2]? arg[2][3] : 0;
  a42=(a39*a41);
  a38=(a38+a42);
  a43=12.;
  a44=(a43*a31);
  a45=(a44*a13);
  a38=(a38+a45);
  a45=(a43*a27);
  a46=(a45*a17);
  a38=(a38-a46);
  a46=38.;
  a46=(a46*a06);
  a38=(a38-a46);
  a38=(a32*a38);
  a00=(a00-a38);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a38=2.7129679869777538e-02;
  a39=(a39*a37);
  a36=(a36+a39);
  a34=(a34*a40);
  a36=(a36+a34);
  a36=(a36+a42);
  a42=(a44*a06);
  a36=(a36-a42);
  a42=(a43*a24);
  a34=(a42*a17);
  a36=(a36+a34);
  a34=60.;
  a34=(a34*a13);
  a36=(a36-a34);
  a36=(a38*a36);
  a00=(a00-a36);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a36=2.1459227467811159e-02;
  a34=arg[2]? arg[2][4] : 0;
  a39=arg[2]? arg[2][5] : 0;
  a46=(a34+a39);
  a47=arg[2]? arg[2][6] : 0;
  a46=(a46+a47);
  a48=arg[2]? arg[2][7] : 0;
  a46=(a46+a48);
  a49=(a45*a06);
  a46=(a46+a49);
  a49=(a42*a13);
  a46=(a46-a49);
  a49=50.;
  a49=(a49*a17);
  a46=(a46-a49);
  a46=(a36*a46);
  a00=(a00-a46);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a46=1.0415581710238517e+00;
  a49=-2.1800000000000000e-01;
  a50=(a49*a34);
  a51=2.1800000000000000e-01;
  a52=(a51*a39);
  a50=(a50+a52);
  a49=(a49*a47);
  a50=(a50+a49);
  a51=(a51*a48);
  a50=(a50+a51);
  a51=2.3544000000000000e+00;
  a49=(a51*a04);
  a52=(a49*a10);
  a50=(a50-a52);
  a52=7.0000000000000007e-02;
  a53=(a52*a24);
  a50=(a50-a53);
  a50=(a46*a50);
  a00=(a00-a50);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][10] : 0;
  a50=8.9285714285714279e-01;
  a53=-1.2000000000000000e-01;
  a34=(a53*a34);
  a53=(a53*a39);
  a34=(a34+a53);
  a53=1.2000000000000000e-01;
  a47=(a53*a47);
  a34=(a34+a47);
  a53=(a53*a48);
  a34=(a34+a53);
  a53=1.4290000000000003e-01;
  a24=(a53*a24);
  a48=(a24*a31);
  a34=(a34+a48);
  a51=(a51*a03);
  a34=(a34-a51);
  a48=(a52*a27);
  a34=(a34-a48);
  a34=(a50*a34);
  a00=(a00-a34);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][11] : 0;
  a34=1.8880000000000000e-01;
  a35=(a34*a35);
  a48=-1.8880000000000000e-01;
  a37=(a48*a37);
  a35=(a35+a37);
  a48=(a48*a40);
  a35=(a35+a48);
  a34=(a34*a41);
  a35=(a35+a34);
  a34=(a24*a27);
  a35=(a35-a34);
  a52=(a52*a31);
  a35=(a35-a52);
  a35=(a50*a35);
  a00=(a00-a35);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][14]=a00;
  a00=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[3]? arg[3][4] : 0;
  if (res[0]!=0) res[0][16]=a00;
  a00=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][17]=a00;
  a00=arg[3]? arg[3][6] : 0;
  if (res[0]!=0) res[0][18]=a00;
  a00=arg[3]? arg[3][7] : 0;
  if (res[0]!=0) res[0][19]=a00;
  a00=(a08*a09);
  a00=(a00+a14);
  a00=(a13*a00);
  a14=(a03*a23);
  a12=(a12-a14);
  a12=(a17*a12);
  a00=(a00+a12);
  a00=(-a00);
  if (res[1]!=0) res[1][0]=a00;
  a00=(a03*a09);
  a12=(a01*a00);
  a12=(a12-a23);
  a12=(a13*a12);
  a23=(a21*a10);
  a23=(a23+a15);
  a23=(a17*a23);
  a12=(a12-a23);
  a12=(-a12);
  if (res[1]!=0) res[1][1]=a12;
  a12=(a13*a25);
  a23=(a17*a18);
  a12=(a12-a23);
  a12=(-a12);
  if (res[1]!=0) res[1][2]=a12;
  a00=(a00/a04);
  a00=(a27*a00);
  a12=(a03*a10);
  a12=(a12/a04);
  a12=(a31*a12);
  a00=(a00-a12);
  a00=(-a00);
  if (res[1]!=0) res[1][3]=a00;
  a00=(a27*a10);
  a12=(a31*a09);
  a00=(a00+a12);
  if (res[1]!=0) res[1][4]=a00;
  a00=(a27*a33);
  a12=(a31*a28);
  a00=(a00-a12);
  a00=(-a00);
  if (res[1]!=0) res[1][5]=a00;
  a00=(a49*a09);
  a00=(a46*a00);
  if (res[1]!=0) res[1][6]=a00;
  a00=(a10*a05);
  a00=(a13*a00);
  a08=(a06*a08);
  a00=(a00-a08);
  a15=(a15*a04);
  a15=(a17*a15);
  a00=(a00+a15);
  a00=(-a00);
  if (res[1]!=0) res[1][7]=a00;
  a00=(a10*a04);
  a00=(a01*a00);
  a00=(a13*a00);
  a15=(a01*a03);
  a15=(a06*a15);
  a00=(a00-a15);
  a15=(a09*a07);
  a15=(a17*a15);
  a00=(a00+a15);
  a00=(-a00);
  if (res[1]!=0) res[1][8]=a00;
  a00=(a13*a19);
  a15=(a06*a04);
  a00=(a00+a15);
  a29=(a17*a29);
  a00=(a00+a29);
  if (res[1]!=0) res[1][9]=a00;
  a00=(a26/a04);
  a00=(a00*a03);
  a00=(a10+a00);
  a00=(a27*a00);
  a29=(a30/a04);
  a29=(a29*a03);
  a29=(a09+a29);
  a29=(a31*a29);
  a00=(a00+a29);
  a00=(-a00);
  if (res[1]!=0) res[1][10]=a00;
  a00=(a28/a04);
  a00=(a00*a03);
  a00=(a27*a00);
  a29=(a33/a04);
  a29=(a29*a03);
  a29=(a31*a29);
  a00=(a00+a29);
  a00=(-a00);
  if (res[1]!=0) res[1][11]=a00;
  a51=(a10*a51);
  a46=(a46*a51);
  a46=(-a46);
  if (res[1]!=0) res[1][12]=a46;
  a49=(a50*a49);
  if (res[1]!=0) res[1][13]=a49;
  a49=(a10*a02);
  a46=(a09*a01);
  a51=(a03*a46);
  a49=(a49-a51);
  a49=(a17*a49);
  a51=(a04*a01);
  a51=(a06*a51);
  a21=(a10*a21);
  a00=(a09*a02);
  a21=(a21+a00);
  a21=(a13*a21);
  a51=(a51+a21);
  a49=(a49-a51);
  a49=(-a49);
  if (res[1]!=0) res[1][14]=a49;
  a04=(a04*a02);
  a04=(a06*a04);
  a19=(a19*a02);
  a19=(a19-a46);
  a19=(a13*a19);
  a04=(a04+a19);
  a02=(a03*a02);
  a02=(a09*a02);
  a01=(a10*a01);
  a02=(a02+a01);
  a02=(a17*a02);
  a04=(a04+a02);
  a04=(-a04);
  if (res[1]!=0) res[1][15]=a04;
  a05=(-a05);
  if (res[1]!=0) res[1][16]=a05;
  a07=(-a07);
  if (res[1]!=0) res[1][17]=a07;
  if (res[1]!=0) res[1][18]=a03;
  a03=1.6688625384277558e+00;
  if (res[1]!=0) res[1][19]=a03;
  a03=(a38*a44);
  if (res[1]!=0) res[1][20]=a03;
  a03=(a36*a45);
  a03=(-a03);
  if (res[1]!=0) res[1][21]=a03;
  a11=(-a11);
  if (res[1]!=0) res[1][22]=a11;
  a20=(-a20);
  if (res[1]!=0) res[1][23]=a20;
  a18=(-a18);
  if (res[1]!=0) res[1][24]=a18;
  a44=(a32*a44);
  a44=(-a44);
  if (res[1]!=0) res[1][25]=a44;
  a44=1.6277807921866523e+00;
  if (res[1]!=0) res[1][26]=a44;
  a44=(a36*a42);
  if (res[1]!=0) res[1][27]=a44;
  a16=(-a16);
  if (res[1]!=0) res[1][28]=a16;
  a22=(-a22);
  if (res[1]!=0) res[1][29]=a22;
  a25=(-a25);
  if (res[1]!=0) res[1][30]=a25;
  a45=(a32*a45);
  if (res[1]!=0) res[1][31]=a45;
  a42=(a38*a42);
  a42=(-a42);
  if (res[1]!=0) res[1][32]=a42;
  a42=1.0729613733905579e+00;
  if (res[1]!=0) res[1][33]=a42;
  a42=-1.;
  if (res[1]!=0) res[1][34]=a42;
  a17=(a43*a17);
  a42=(a38*a17);
  a42=(-a42);
  if (res[1]!=0) res[1][35]=a42;
  a13=(a43*a13);
  a42=(a36*a13);
  if (res[1]!=0) res[1][36]=a42;
  a42=7.2909071971669626e-02;
  if (res[1]!=0) res[1][37]=a42;
  a31=(a53*a31);
  a31=(a50*a31);
  a31=(-a31);
  if (res[1]!=0) res[1][38]=a31;
  a53=(a53*a27);
  a53=(a50*a53);
  if (res[1]!=0) res[1][39]=a53;
  a26=(-a26);
  if (res[1]!=0) res[1][40]=a26;
  a09=(-a09);
  if (res[1]!=0) res[1][41]=a09;
  a28=(-a28);
  if (res[1]!=0) res[1][42]=a28;
  a17=(a32*a17);
  if (res[1]!=0) res[1][43]=a17;
  a43=(a43*a06);
  a36=(a36*a43);
  a36=(-a36);
  if (res[1]!=0) res[1][44]=a36;
  a36=6.2500000000000000e-02;
  if (res[1]!=0) res[1][45]=a36;
  a50=(a50*a24);
  if (res[1]!=0) res[1][46]=a50;
  a30=(-a30);
  if (res[1]!=0) res[1][47]=a30;
  if (res[1]!=0) res[1][48]=a10;
  a33=(-a33);
  if (res[1]!=0) res[1][49]=a33;
  a32=(a32*a13);
  a32=(-a32);
  if (res[1]!=0) res[1][50]=a32;
  a38=(a38*a43);
  if (res[1]!=0) res[1][51]=a38;
  a50=(-a50);
  if (res[1]!=0) res[1][52]=a50;
  if (res[1]!=0) res[1][53]=a36;
  a36=1.;
  if (res[2]!=0) res[2][0]=a36;
  if (res[2]!=0) res[2][1]=a36;
  if (res[2]!=0) res[2][2]=a36;
  if (res[2]!=0) res[2][3]=a36;
  if (res[2]!=0) res[2][4]=a36;
  if (res[2]!=0) res[2][5]=a36;
  if (res[2]!=0) res[2][6]=a36;
  if (res[2]!=0) res[2][7]=a36;
  if (res[2]!=0) res[2][8]=a36;
  if (res[2]!=0) res[2][9]=a36;
  if (res[2]!=0) res[2][10]=a36;
  if (res[2]!=0) res[2][11]=a36;
  a36=-3.1049626701800614e-02;
  if (res[3]!=0) res[3][0]=a36;
  a50=-1.9180683667932720e-02;
  if (res[3]!=0) res[3][1]=a50;
  a38=-1.6857142857142857e-01;
  if (res[3]!=0) res[3][2]=a38;
  if (res[3]!=0) res[3][3]=a36;
  a36=1.9180683667932720e-02;
  if (res[3]!=0) res[3][4]=a36;
  a43=1.6857142857142857e-01;
  if (res[3]!=0) res[3][5]=a43;
  a32=3.1049626701800614e-02;
  if (res[3]!=0) res[3][6]=a32;
  if (res[3]!=0) res[3][7]=a50;
  if (res[3]!=0) res[3][8]=a43;
  if (res[3]!=0) res[3][9]=a32;
  if (res[3]!=0) res[3][10]=a36;
  if (res[3]!=0) res[3][11]=a38;
  a38=-2.1459227467811159e-02;
  if (res[3]!=0) res[3][12]=a38;
  a36=2.2705968128319967e-01;
  if (res[3]!=0) res[3][13]=a36;
  a32=1.0714285714285714e-01;
  if (res[3]!=0) res[3][14]=a32;
  if (res[3]!=0) res[3][15]=a38;
  a43=-2.2705968128319967e-01;
  if (res[3]!=0) res[3][16]=a43;
  if (res[3]!=0) res[3][17]=a32;
  if (res[3]!=0) res[3][18]=a38;
  if (res[3]!=0) res[3][19]=a36;
  a36=-1.0714285714285714e-01;
  if (res[3]!=0) res[3][20]=a36;
  if (res[3]!=0) res[3][21]=a38;
  if (res[3]!=0) res[3][22]=a43;
  if (res[3]!=0) res[3][23]=a36;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov2heavy_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int bluerov2heavy_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real bluerov2heavy_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2heavy_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2heavy_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2heavy_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2heavy_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
