/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov2heavy_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {20, 1, 1};

/* bluerov2heavy_impl_dae_fun:(i0[12],i1[12],i2[8],i3[8],i4[],i5[0])->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][4] : 0;
  a04=cos(a03);
  a05=(a02*a04);
  a06=arg[0]? arg[0][6] : 0;
  a05=(a05*a06);
  a03=sin(a03);
  a07=(a02*a03);
  a08=arg[0]? arg[0][3] : 0;
  a09=sin(a08);
  a07=(a07*a09);
  a01=sin(a01);
  a08=cos(a08);
  a10=(a01*a08);
  a07=(a07-a10);
  a10=arg[0]? arg[0][7] : 0;
  a07=(a07*a10);
  a05=(a05+a07);
  a07=(a01*a09);
  a11=(a02*a08);
  a12=(a11*a03);
  a07=(a07+a12);
  a12=arg[0]? arg[0][8] : 0;
  a07=(a07*a12);
  a05=(a05+a07);
  a00=(a00-a05);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a05=(a01*a04);
  a05=(a05*a06);
  a07=(a09*a03);
  a13=(a07*a01);
  a11=(a11+a13);
  a11=(a11*a10);
  a05=(a05+a11);
  a01=(a03*a01);
  a01=(a01*a08);
  a02=(a02*a09);
  a01=(a01-a02);
  a01=(a01*a12);
  a05=(a05+a01);
  a00=(a00-a05);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a05=(a04*a09);
  a05=(a05*a10);
  a01=(a03*a06);
  a05=(a05-a01);
  a01=(a04*a08);
  a01=(a01*a12);
  a05=(a05+a01);
  a00=(a00-a05);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a05=arg[0]? arg[0][9] : 0;
  a07=(a07/a04);
  a01=arg[0]? arg[0][10] : 0;
  a07=(a07*a01);
  a07=(a05+a07);
  a02=(a08*a03);
  a02=(a02/a04);
  a11=arg[0]? arg[0][11] : 0;
  a02=(a02*a11);
  a07=(a07+a02);
  a00=(a00-a07);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a07=(a08*a01);
  a02=(a09*a11);
  a07=(a07-a02);
  a00=(a00-a07);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a07=(a09/a04);
  a07=(a07*a01);
  a08=(a08/a04);
  a08=(a08*a11);
  a07=(a07+a08);
  a00=(a00-a07);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a07=4.3917435221783048e-02;
  a08=7.0699999999999996e-01;
  a02=arg[2]? arg[2][0] : 0;
  a13=(a08*a02);
  a14=arg[2]? arg[2][1] : 0;
  a15=(a08*a14);
  a15=(a13+a15);
  a16=-7.0699999999999996e-01;
  a17=arg[2]? arg[2][2] : 0;
  a18=(a16*a17);
  a15=(a15+a18);
  a18=arg[2]? arg[2][3] : 0;
  a19=(a16*a18);
  a15=(a15+a19);
  a20=12.;
  a21=(a20*a11);
  a22=(a21*a10);
  a15=(a15+a22);
  a22=(a20*a01);
  a23=(a22*a12);
  a15=(a15-a23);
  a23=38.;
  a23=(a23*a06);
  a15=(a15-a23);
  a07=(a07*a15);
  a00=(a00-a07);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a07=2.7129679869777538e-02;
  a16=(a16*a14);
  a13=(a13+a16);
  a08=(a08*a17);
  a13=(a13+a08);
  a13=(a13+a19);
  a21=(a21*a06);
  a13=(a13-a21);
  a20=(a20*a05);
  a21=(a20*a12);
  a13=(a13+a21);
  a21=60.;
  a21=(a21*a10);
  a13=(a13-a21);
  a07=(a07*a13);
  a00=(a00-a07);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a07=2.1459227467811159e-02;
  a13=arg[2]? arg[2][4] : 0;
  a21=arg[2]? arg[2][5] : 0;
  a19=(a13+a21);
  a08=arg[2]? arg[2][6] : 0;
  a19=(a19+a08);
  a16=arg[2]? arg[2][7] : 0;
  a19=(a19+a16);
  a22=(a22*a06);
  a19=(a19+a22);
  a20=(a20*a10);
  a19=(a19-a20);
  a20=50.;
  a20=(a20*a12);
  a19=(a19-a20);
  a07=(a07*a19);
  a00=(a00-a07);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a07=1.0415581710238517e+00;
  a19=-2.1800000000000000e-01;
  a20=(a19*a13);
  a12=2.1800000000000000e-01;
  a10=(a12*a21);
  a20=(a20+a10);
  a19=(a19*a08);
  a20=(a20+a19);
  a12=(a12*a16);
  a20=(a20+a12);
  a12=2.3544000000000000e+00;
  a04=(a12*a04);
  a04=(a04*a09);
  a20=(a20-a04);
  a04=7.0000000000000007e-02;
  a09=(a04*a05);
  a20=(a20-a09);
  a07=(a07*a20);
  a00=(a00-a07);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][10] : 0;
  a07=8.9285714285714279e-01;
  a20=-1.2000000000000000e-01;
  a13=(a20*a13);
  a20=(a20*a21);
  a13=(a13+a20);
  a20=1.2000000000000000e-01;
  a08=(a20*a08);
  a13=(a13+a08);
  a20=(a20*a16);
  a13=(a13+a20);
  a20=1.4290000000000003e-01;
  a20=(a20*a05);
  a05=(a20*a11);
  a13=(a13+a05);
  a12=(a12*a03);
  a13=(a13-a12);
  a12=(a04*a01);
  a13=(a13-a12);
  a13=(a07*a13);
  a00=(a00-a13);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][11] : 0;
  a13=1.8880000000000000e-01;
  a02=(a13*a02);
  a12=-1.8880000000000000e-01;
  a14=(a12*a14);
  a02=(a02+a14);
  a12=(a12*a17);
  a02=(a02+a12);
  a13=(a13*a18);
  a02=(a02+a13);
  a20=(a20*a01);
  a02=(a02-a20);
  a04=(a04*a11);
  a02=(a02-a04);
  a07=(a07*a02);
  a00=(a00-a07);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][14]=a00;
  a00=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[3]? arg[3][4] : 0;
  if (res[0]!=0) res[0][16]=a00;
  a00=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][17]=a00;
  a00=arg[3]? arg[3][6] : 0;
  if (res[0]!=0) res[0][18]=a00;
  a00=arg[3]? arg[3][7] : 0;
  if (res[0]!=0) res[0][19]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov2heavy_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int bluerov2heavy_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov2heavy_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2heavy_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2heavy_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2heavy_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2heavy_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
