/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov2heavy_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[69] = 
  {20, 12, 0, 0, 0, 0, 7, 14,
  16, 22, 28, 34, 40, 47, 54, 0,
  1, 2, 3, 4, 5, 9, 0, 1,
  2, 3, 5, 9, 10, 0, 1, 0,
  1, 2, 6, 7, 8, 0, 1, 2,
  6, 7, 8, 0, 1, 2, 6, 7,
  8, 3, 7, 8, 9, 10, 11, 3,
  4, 5, 6, 8, 10, 11, 3, 4,
  5, 6, 7, 10, 11};
static const casadi_int casadi_s5[27] = 
  {20, 12, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11};
static const casadi_int casadi_s6[35] = 
  {20, 8, 0, 3, 6, 9, 12, 15,
  18, 21, 24, 6, 7, 11, 6, 7,
  11, 6, 7, 11, 6, 7, 11, 8,
  9, 10, 8, 9, 10, 8, 9, 10,
  8, 9, 10};
static const casadi_int casadi_s7[19] = 
  {20, 8, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 12, 13, 14, 15, 16,
  17, 18, 19};

/* bluerov2heavy_impl_dae_jac_x_xdot_u_z:(i0[12],i1[12],i2[8],i3[8],i4[],i5[0])->(o0[20x12,54nz],o1[20x12,12nz],o2[20x8,24nz],o3[20x8,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=arg[0]? arg[0][7] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][4] : 0;
  a04=sin(a03);
  a05=(a02*a04);
  a06=arg[0]? arg[0][3] : 0;
  a07=cos(a06);
  a08=(a05*a07);
  a01=sin(a01);
  a06=sin(a06);
  a09=(a01*a06);
  a08=(a08+a09);
  a08=(a00*a08);
  a10=arg[0]? arg[0][8] : 0;
  a11=(a01*a07);
  a12=(a02*a06);
  a13=(a04*a12);
  a13=(a11-a13);
  a13=(a10*a13);
  a08=(a08+a13);
  a08=(-a08);
  if (res[0]!=0) res[0][0]=a08;
  a08=(a04*a07);
  a13=(a01*a08);
  a13=(a13-a12);
  a13=(a00*a13);
  a14=(a04*a01);
  a15=(a14*a06);
  a16=(a02*a07);
  a15=(a15+a16);
  a15=(a10*a15);
  a13=(a13-a15);
  a13=(-a13);
  if (res[0]!=0) res[0][1]=a13;
  a03=cos(a03);
  a13=(a03*a07);
  a15=(a00*a13);
  a17=(a03*a06);
  a18=(a10*a17);
  a15=(a15-a18);
  a15=(-a15);
  if (res[0]!=0) res[0][2]=a15;
  a15=arg[0]? arg[0][10] : 0;
  a08=(a08/a03);
  a08=(a15*a08);
  a18=arg[0]? arg[0][11] : 0;
  a19=(a04*a06);
  a19=(a19/a03);
  a19=(a18*a19);
  a08=(a08-a19);
  a08=(-a08);
  if (res[0]!=0) res[0][3]=a08;
  a08=(a15*a06);
  a19=(a18*a07);
  a08=(a08+a19);
  if (res[0]!=0) res[0][4]=a08;
  a08=(a07/a03);
  a19=(a15*a08);
  a20=(a06/a03);
  a21=(a18*a20);
  a19=(a19-a21);
  a19=(-a19);
  if (res[0]!=0) res[0][5]=a19;
  a19=1.0415581710238517e+00;
  a21=2.3544000000000000e+00;
  a22=(a21*a03);
  a23=(a22*a07);
  a23=(a19*a23);
  if (res[0]!=0) res[0][6]=a23;
  a23=(a02*a03);
  a24=(a06*a23);
  a24=(a00*a24);
  a25=arg[0]? arg[0][6] : 0;
  a26=(a25*a05);
  a24=(a24-a26);
  a26=(a16*a03);
  a26=(a10*a26);
  a24=(a24+a26);
  a24=(-a24);
  if (res[0]!=0) res[0][7]=a24;
  a24=(a06*a03);
  a24=(a01*a24);
  a24=(a00*a24);
  a26=(a01*a04);
  a26=(a25*a26);
  a24=(a24-a26);
  a26=(a01*a03);
  a27=(a07*a26);
  a27=(a10*a27);
  a24=(a24+a27);
  a24=(-a24);
  if (res[0]!=0) res[0][8]=a24;
  a24=(a06*a04);
  a27=(a00*a24);
  a28=(a25*a03);
  a27=(a27+a28);
  a28=(a07*a04);
  a29=(a10*a28);
  a27=(a27+a29);
  if (res[0]!=0) res[0][9]=a27;
  a27=(a24/a03);
  a29=(a27/a03);
  a29=(a29*a04);
  a29=(a06+a29);
  a29=(a15*a29);
  a28=(a28/a03);
  a30=(a28/a03);
  a30=(a30*a04);
  a30=(a07+a30);
  a30=(a18*a30);
  a29=(a29+a30);
  a29=(-a29);
  if (res[0]!=0) res[0][10]=a29;
  a29=(a20/a03);
  a29=(a29*a04);
  a29=(a15*a29);
  a30=(a08/a03);
  a30=(a30*a04);
  a30=(a18*a30);
  a29=(a29+a30);
  a29=(-a29);
  if (res[0]!=0) res[0][11]=a29;
  a21=(a21*a04);
  a21=(a06*a21);
  a19=(a19*a21);
  a19=(-a19);
  if (res[0]!=0) res[0][12]=a19;
  a19=8.9285714285714279e-01;
  a22=(a19*a22);
  if (res[0]!=0) res[0][13]=a22;
  a22=(a06*a02);
  a21=(a07*a01);
  a29=(a04*a21);
  a22=(a22-a29);
  a22=(a10*a22);
  a29=(a03*a01);
  a29=(a25*a29);
  a30=(a06*a14);
  a31=(a07*a02);
  a30=(a30+a31);
  a30=(a00*a30);
  a29=(a29+a30);
  a22=(a22-a29);
  a22=(-a22);
  if (res[0]!=0) res[0][14]=a22;
  a03=(a03*a02);
  a03=(a25*a03);
  a22=(a24*a02);
  a22=(a22-a21);
  a22=(a00*a22);
  a03=(a03+a22);
  a02=(a04*a02);
  a02=(a07*a02);
  a22=(a06*a01);
  a02=(a02+a22);
  a02=(a10*a02);
  a03=(a03+a02);
  a03=(-a03);
  if (res[0]!=0) res[0][15]=a03;
  a23=(-a23);
  if (res[0]!=0) res[0][16]=a23;
  a26=(-a26);
  if (res[0]!=0) res[0][17]=a26;
  if (res[0]!=0) res[0][18]=a04;
  a26=1.6688625384277558e+00;
  if (res[0]!=0) res[0][19]=a26;
  a26=2.7129679869777538e-02;
  a23=12.;
  a03=(a23*a18);
  a02=(a26*a03);
  if (res[0]!=0) res[0][20]=a02;
  a02=2.1459227467811159e-02;
  a22=(a23*a15);
  a21=(a02*a22);
  a21=(-a21);
  if (res[0]!=0) res[0][21]=a21;
  a05=(a05*a06);
  a05=(a05-a11);
  a05=(-a05);
  if (res[0]!=0) res[0][22]=a05;
  a24=(a24*a01);
  a24=(a16+a24);
  a24=(-a24);
  if (res[0]!=0) res[0][23]=a24;
  a17=(-a17);
  if (res[0]!=0) res[0][24]=a17;
  a17=4.3917435221783048e-02;
  a03=(a17*a03);
  a03=(-a03);
  if (res[0]!=0) res[0][25]=a03;
  a03=1.6277807921866523e+00;
  if (res[0]!=0) res[0][26]=a03;
  a03=arg[0]? arg[0][9] : 0;
  a24=(a23*a03);
  a01=(a02*a24);
  if (res[0]!=0) res[0][27]=a01;
  a16=(a16*a04);
  a09=(a09+a16);
  a09=(-a09);
  if (res[0]!=0) res[0][28]=a09;
  a14=(a14*a07);
  a14=(a14-a12);
  a14=(-a14);
  if (res[0]!=0) res[0][29]=a14;
  a13=(-a13);
  if (res[0]!=0) res[0][30]=a13;
  a22=(a17*a22);
  if (res[0]!=0) res[0][31]=a22;
  a24=(a26*a24);
  a24=(-a24);
  if (res[0]!=0) res[0][32]=a24;
  a24=1.0729613733905579e+00;
  if (res[0]!=0) res[0][33]=a24;
  a24=-1.;
  if (res[0]!=0) res[0][34]=a24;
  a10=(a23*a10);
  a24=(a26*a10);
  a24=(-a24);
  if (res[0]!=0) res[0][35]=a24;
  a00=(a23*a00);
  a24=(a02*a00);
  if (res[0]!=0) res[0][36]=a24;
  a24=7.2909071971669626e-02;
  if (res[0]!=0) res[0][37]=a24;
  a24=1.4290000000000003e-01;
  a18=(a24*a18);
  a18=(a19*a18);
  a18=(-a18);
  if (res[0]!=0) res[0][38]=a18;
  a15=(a24*a15);
  a15=(a19*a15);
  if (res[0]!=0) res[0][39]=a15;
  a27=(-a27);
  if (res[0]!=0) res[0][40]=a27;
  a07=(-a07);
  if (res[0]!=0) res[0][41]=a07;
  a20=(-a20);
  if (res[0]!=0) res[0][42]=a20;
  a10=(a17*a10);
  if (res[0]!=0) res[0][43]=a10;
  a23=(a23*a25);
  a02=(a02*a23);
  a02=(-a02);
  if (res[0]!=0) res[0][44]=a02;
  a02=6.2500000000000000e-02;
  if (res[0]!=0) res[0][45]=a02;
  a24=(a24*a03);
  a19=(a19*a24);
  if (res[0]!=0) res[0][46]=a19;
  a28=(-a28);
  if (res[0]!=0) res[0][47]=a28;
  if (res[0]!=0) res[0][48]=a06;
  a08=(-a08);
  if (res[0]!=0) res[0][49]=a08;
  a17=(a17*a00);
  a17=(-a17);
  if (res[0]!=0) res[0][50]=a17;
  a26=(a26*a23);
  if (res[0]!=0) res[0][51]=a26;
  a19=(-a19);
  if (res[0]!=0) res[0][52]=a19;
  if (res[0]!=0) res[0][53]=a02;
  a02=1.;
  if (res[1]!=0) res[1][0]=a02;
  if (res[1]!=0) res[1][1]=a02;
  if (res[1]!=0) res[1][2]=a02;
  if (res[1]!=0) res[1][3]=a02;
  if (res[1]!=0) res[1][4]=a02;
  if (res[1]!=0) res[1][5]=a02;
  if (res[1]!=0) res[1][6]=a02;
  if (res[1]!=0) res[1][7]=a02;
  if (res[1]!=0) res[1][8]=a02;
  if (res[1]!=0) res[1][9]=a02;
  if (res[1]!=0) res[1][10]=a02;
  if (res[1]!=0) res[1][11]=a02;
  a19=-3.1049626701800614e-02;
  if (res[2]!=0) res[2][0]=a19;
  a26=-1.9180683667932720e-02;
  if (res[2]!=0) res[2][1]=a26;
  a23=-1.6857142857142857e-01;
  if (res[2]!=0) res[2][2]=a23;
  if (res[2]!=0) res[2][3]=a19;
  a19=1.9180683667932720e-02;
  if (res[2]!=0) res[2][4]=a19;
  a17=1.6857142857142857e-01;
  if (res[2]!=0) res[2][5]=a17;
  a00=3.1049626701800614e-02;
  if (res[2]!=0) res[2][6]=a00;
  if (res[2]!=0) res[2][7]=a26;
  if (res[2]!=0) res[2][8]=a17;
  if (res[2]!=0) res[2][9]=a00;
  if (res[2]!=0) res[2][10]=a19;
  if (res[2]!=0) res[2][11]=a23;
  a23=-2.1459227467811159e-02;
  if (res[2]!=0) res[2][12]=a23;
  a19=2.2705968128319967e-01;
  if (res[2]!=0) res[2][13]=a19;
  a00=1.0714285714285714e-01;
  if (res[2]!=0) res[2][14]=a00;
  if (res[2]!=0) res[2][15]=a23;
  a17=-2.2705968128319967e-01;
  if (res[2]!=0) res[2][16]=a17;
  if (res[2]!=0) res[2][17]=a00;
  if (res[2]!=0) res[2][18]=a23;
  if (res[2]!=0) res[2][19]=a19;
  a19=-1.0714285714285714e-01;
  if (res[2]!=0) res[2][20]=a19;
  if (res[2]!=0) res[2][21]=a23;
  if (res[2]!=0) res[2][22]=a17;
  if (res[2]!=0) res[2][23]=a19;
  if (res[3]!=0) res[3][0]=a02;
  if (res[3]!=0) res[3][1]=a02;
  if (res[3]!=0) res[3][2]=a02;
  if (res[3]!=0) res[3][3]=a02;
  if (res[3]!=0) res[3][4]=a02;
  if (res[3]!=0) res[3][5]=a02;
  if (res[3]!=0) res[3][6]=a02;
  if (res[3]!=0) res[3][7]=a02;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov2heavy_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int bluerov2heavy_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real bluerov2heavy_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2heavy_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2heavy_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2heavy_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2heavy_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
