/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov2heavy_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {20, 1, 1};

/* bluerov2heavy_expl_vde_adj:(i0[12],i1[12],i2[8],i3[0])->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a01=arg[0]? arg[0][3] : 0;
  a02=cos(a01);
  a03=6.6749999999999998e+00;
  a04=arg[0]? arg[0][4] : 0;
  a05=cos(a04);
  a06=(a03*a05);
  a07=2.7502750275027504e-02;
  a08=arg[1]? arg[1][7] : 0;
  a07=(a07*a08);
  a08=(a06*a07);
  a08=(a02*a08);
  a09=2.2563000000000004e+00;
  a10=(a09*a05);
  a11=1.0415581710238517e+00;
  a12=arg[1]? arg[1][9] : 0;
  a11=(a11*a12);
  a10=(a10*a11);
  a10=(a02*a10);
  a01=sin(a01);
  a12=arg[1]? arg[1][8] : 0;
  a13=1.1500000000000000e+01;
  a14=arg[0]? arg[0][8] : 0;
  a00=(a14<a00);
  a15=3.4600000000000001e+01;
  a15=(a00?a15:0);
  a16=(!a00);
  a17=2.2449999999999999e+01;
  a17=(a16?a17:0);
  a15=(a15+a17);
  a15=(a13+a15);
  a12=(a12/a15);
  a06=(a06*a12);
  a06=(a01*a06);
  a10=(a10+a06);
  a08=(a08-a10);
  a10=arg[0]? arg[0][11] : 0;
  a06=arg[1]? arg[1][5] : 0;
  a15=(a10*a06);
  a17=(a15/a05);
  a17=(a01*a17);
  a08=(a08-a17);
  a17=arg[0]? arg[0][10] : 0;
  a18=(a17*a06);
  a19=(a18/a05);
  a19=(a02*a19);
  a08=(a08+a19);
  a19=arg[1]? arg[1][4] : 0;
  a20=(a10*a19);
  a20=(a02*a20);
  a08=(a08-a20);
  a20=(a17*a19);
  a20=(a01*a20);
  a08=(a08-a20);
  a04=sin(a04);
  a20=arg[1]? arg[1][3] : 0;
  a21=(a10*a20);
  a22=(a21/a05);
  a23=(a04*a22);
  a23=(a01*a23);
  a08=(a08-a23);
  a23=(a17*a20);
  a24=(a23/a05);
  a25=(a04*a24);
  a25=(a02*a25);
  a08=(a08+a25);
  a25=arg[1]? arg[1][2] : 0;
  a26=(a14*a25);
  a27=(a05*a26);
  a27=(a01*a27);
  a08=(a08-a27);
  a27=arg[0]? arg[0][7] : 0;
  a28=(a27*a25);
  a29=(a05*a28);
  a29=(a02*a29);
  a08=(a08+a29);
  a29=arg[0]? arg[0][5] : 0;
  a30=cos(a29);
  a31=arg[1]? arg[1][1] : 0;
  a32=(a14*a31);
  a33=(a30*a32);
  a33=(a02*a33);
  a08=(a08-a33);
  a29=sin(a29);
  a33=(a04*a29);
  a34=(a33*a32);
  a34=(a01*a34);
  a08=(a08-a34);
  a34=(a27*a31);
  a35=(a29*a34);
  a36=(a04*a35);
  a36=(a02*a36);
  a08=(a08+a36);
  a36=(a30*a34);
  a36=(a01*a36);
  a08=(a08-a36);
  a36=arg[1]? arg[1][0] : 0;
  a37=(a14*a36);
  a38=(a04*a37);
  a39=(a30*a38);
  a39=(a01*a39);
  a08=(a08-a39);
  a39=(a29*a37);
  a39=(a02*a39);
  a08=(a08+a39);
  a39=(a27*a36);
  a40=(a29*a39);
  a40=(a01*a40);
  a08=(a08+a40);
  a40=(a30*a04);
  a41=(a40*a39);
  a41=(a02*a41);
  a08=(a08+a41);
  if (res[0]!=0) res[0][3]=a08;
  a08=(a01*a11);
  a08=(a09*a08);
  a08=(a04*a08);
  a41=8.9285714285714279e-01;
  a42=arg[1]? arg[1][10] : 0;
  a42=(a41*a42);
  a09=(a09*a42);
  a09=(a05*a09);
  a08=(a08-a09);
  a09=(a02*a12);
  a09=(a03*a09);
  a09=(a04*a09);
  a08=(a08-a09);
  a09=(a01*a07);
  a09=(a03*a09);
  a09=(a04*a09);
  a08=(a08-a09);
  a09=4.4903457566232603e-02;
  a43=arg[1]? arg[1][6] : 0;
  a09=(a09*a43);
  a03=(a03*a09);
  a03=(a05*a03);
  a08=(a08-a03);
  a03=(a02/a05);
  a43=(a03/a05);
  a43=(a43*a15);
  a43=(a04*a43);
  a08=(a08+a43);
  a43=(a01/a05);
  a15=(a43/a05);
  a15=(a15*a18);
  a15=(a04*a15);
  a08=(a08+a15);
  a15=(a02*a04);
  a15=(a15/a05);
  a18=(a15/a05);
  a18=(a18*a21);
  a18=(a04*a18);
  a08=(a08+a18);
  a22=(a02*a22);
  a22=(a05*a22);
  a08=(a08+a22);
  a22=(a01*a04);
  a18=(a22/a05);
  a21=(a18/a05);
  a21=(a21*a23);
  a21=(a04*a21);
  a08=(a08+a21);
  a24=(a01*a24);
  a24=(a05*a24);
  a08=(a08+a24);
  a26=(a02*a26);
  a26=(a04*a26);
  a08=(a08-a26);
  a26=arg[0]? arg[0][6] : 0;
  a24=(a26*a25);
  a24=(a05*a24);
  a08=(a08-a24);
  a28=(a01*a28);
  a28=(a04*a28);
  a08=(a08-a28);
  a28=(a02*a32);
  a24=(a29*a28);
  a24=(a05*a24);
  a08=(a08+a24);
  a35=(a01*a35);
  a35=(a05*a35);
  a08=(a08+a35);
  a35=(a26*a31);
  a24=(a29*a35);
  a24=(a04*a24);
  a08=(a08-a24);
  a24=(a30*a02);
  a21=(a24*a37);
  a21=(a05*a21);
  a08=(a08+a21);
  a21=(a01*a39);
  a23=(a30*a21);
  a23=(a05*a23);
  a08=(a08+a23);
  a23=(a26*a36);
  a44=(a30*a23);
  a44=(a04*a44);
  a08=(a08-a44);
  if (res[0]!=0) res[0][4]=a08;
  a32=(a01*a32);
  a32=(a29*a32);
  a28=(a04*a28);
  a28=(a30*a28);
  a32=(a32+a28);
  a28=(a22*a34);
  a28=(a30*a28);
  a32=(a32+a28);
  a34=(a02*a34);
  a34=(a29*a34);
  a32=(a32-a34);
  a35=(a05*a35);
  a35=(a30*a35);
  a32=(a32+a35);
  a38=(a02*a38);
  a38=(a29*a38);
  a32=(a32-a38);
  a37=(a01*a37);
  a37=(a30*a37);
  a32=(a32+a37);
  a39=(a02*a39);
  a39=(a30*a39);
  a32=(a32-a39);
  a21=(a04*a21);
  a21=(a29*a21);
  a32=(a32-a21);
  a23=(a05*a23);
  a23=(a29*a23);
  a32=(a32-a23);
  if (res[0]!=0) res[0][5]=a32;
  a32=(a13*a17);
  a23=(a32*a12);
  a21=(a13*a10);
  a39=(a21*a07);
  a23=(a23-a39);
  a39=casadi_sign(a26);
  a37=3.1010000000000002e+01;
  a38=(a37*a26);
  a38=(a38*a09);
  a39=(a39*a38);
  a23=(a23-a39);
  a39=casadi_fabs(a26);
  a39=(a39*a09);
  a37=(a37*a39);
  a23=(a23-a37);
  a37=3.8950000000000003e+01;
  a37=(a37*a09);
  a23=(a23-a37);
  a37=(a04*a25);
  a23=(a23-a37);
  a37=(a29*a05);
  a37=(a37*a31);
  a23=(a23+a37);
  a37=(a30*a05);
  a37=(a37*a36);
  a23=(a23+a37);
  if (res[0]!=0) res[0][6]=a23;
  a21=(a21*a09);
  a23=arg[0]? arg[0][9] : 0;
  a37=(a13*a23);
  a39=(a37*a12);
  a38=casadi_sign(a27);
  a35=3.6950000000000003e+01;
  a34=(a35*a27);
  a34=(a34*a07);
  a38=(a38*a34);
  a39=(a39+a38);
  a38=casadi_fabs(a27);
  a38=(a38*a07);
  a35=(a35*a38);
  a39=(a39+a35);
  a35=6.0109999999999999e+01;
  a35=(a35*a07);
  a39=(a39+a35);
  a21=(a21-a39);
  a39=(a05*a01);
  a39=(a39*a25);
  a21=(a21+a39);
  a22=(a22*a29);
  a22=(a24+a22);
  a22=(a22*a31);
  a21=(a21+a22);
  a40=(a40*a01);
  a22=(a29*a02);
  a40=(a40-a22);
  a40=(a40*a36);
  a21=(a21+a40);
  if (res[0]!=0) res[0][7]=a21;
  a37=(a37*a07);
  a21=casadi_sign(a14);
  a40=1.1386000000000000e+02;
  a40=(a00?a40:0);
  a22=7.6689999999999998e+01;
  a22=(a16?a22:0);
  a40=(a40+a22);
  a22=(a40*a14);
  a22=(a22*a12);
  a21=(a21*a22);
  a22=casadi_fabs(a14);
  a22=(a22*a12);
  a40=(a40*a22);
  a21=(a21+a40);
  a40=4.9500000000000000e+01;
  a00=(a00?a40:0);
  a40=5.0619999999999997e+01;
  a16=(a16?a40:0);
  a00=(a00+a16);
  a00=(a00*a12);
  a21=(a21+a00);
  a37=(a37-a21);
  a32=(a32*a09);
  a37=(a37-a32);
  a05=(a05*a02);
  a05=(a05*a25);
  a37=(a37+a05);
  a33=(a33*a02);
  a30=(a30*a01);
  a33=(a33-a30);
  a33=(a33*a31);
  a37=(a37+a33);
  a29=(a29*a01);
  a24=(a24*a04);
  a29=(a29+a24);
  a29=(a29*a36);
  a37=(a37+a29);
  if (res[0]!=0) res[0][8]=a37;
  a37=1.4290000000000003e-01;
  a29=(a10*a42);
  a29=(a37*a29);
  a36=arg[1]? arg[1][11] : 0;
  a41=(a41*a36);
  a36=(a17*a41);
  a36=(a37*a36);
  a29=(a29-a36);
  a36=casadi_sign(a23);
  a24=2.0800000000000001e+00;
  a04=(a24*a23);
  a04=(a04*a11);
  a36=(a36*a04);
  a29=(a29-a36);
  a36=casadi_fabs(a23);
  a36=(a36*a11);
  a24=(a24*a36);
  a29=(a29-a24);
  a24=(a27*a12);
  a24=(a13*a24);
  a29=(a29-a24);
  a24=(a14*a07);
  a24=(a13*a24);
  a29=(a29+a24);
  a29=(a29+a20);
  if (res[0]!=0) res[0][9]=a29;
  a29=(a26*a12);
  a29=(a13*a29);
  a37=(a37*a23);
  a23=(a37*a41);
  a24=casadi_sign(a17);
  a36=2.4199999999999999e+00;
  a04=(a36*a17);
  a04=(a04*a42);
  a24=(a24*a04);
  a23=(a23+a24);
  a17=casadi_fabs(a17);
  a17=(a17*a42);
  a17=(a36*a17);
  a23=(a23+a17);
  a29=(a29-a23);
  a14=(a14*a09);
  a14=(a13*a14);
  a29=(a29-a14);
  a43=(a43*a06);
  a29=(a29+a43);
  a02=(a02*a19);
  a29=(a29+a02);
  a18=(a18*a20);
  a29=(a29+a18);
  if (res[0]!=0) res[0][10]=a29;
  a37=(a37*a42);
  a29=casadi_sign(a10);
  a18=(a36*a10);
  a18=(a18*a41);
  a29=(a29*a18);
  a10=casadi_fabs(a10);
  a10=(a10*a41);
  a36=(a36*a10);
  a29=(a29+a36);
  a37=(a37-a29);
  a26=(a26*a07);
  a26=(a13*a26);
  a37=(a37-a26);
  a27=(a27*a09);
  a13=(a13*a27);
  a37=(a37+a13);
  a03=(a03*a06);
  a37=(a37+a03);
  a01=(a01*a19);
  a37=(a37-a01);
  a15=(a15*a20);
  a37=(a37+a15);
  if (res[0]!=0) res[0][11]=a37;
  a37=1.8880000000000000e-01;
  a37=(a37*a41);
  a15=-6.7000000000000004e-02;
  a20=(a15*a42);
  a01=(a37+a20);
  a19=6.7000000000000004e-02;
  a03=(a19*a11);
  a01=(a01+a03);
  a06=7.0699999999999996e-01;
  a13=(a06*a07);
  a01=(a01+a13);
  a06=(a06*a09);
  a01=(a01+a06);
  if (res[0]!=0) res[0][12]=a01;
  a01=-1.8880000000000000e-01;
  a01=(a01*a41);
  a20=(a01+a20);
  a15=(a15*a11);
  a20=(a20+a15);
  a41=-7.0699999999999996e-01;
  a07=(a41*a07);
  a20=(a20+a07);
  a20=(a20+a06);
  if (res[0]!=0) res[0][13]=a20;
  a19=(a19*a42);
  a01=(a01+a19);
  a01=(a01+a03);
  a01=(a01+a13);
  a41=(a41*a09);
  a01=(a01+a41);
  if (res[0]!=0) res[0][14]=a01;
  a37=(a37+a19);
  a37=(a37+a15);
  a37=(a37+a07);
  a37=(a37+a41);
  if (res[0]!=0) res[0][15]=a37;
  a37=-1.2000000000000000e-01;
  a37=(a37*a42);
  a41=-2.1800000000000000e-01;
  a41=(a41*a11);
  a07=(a37+a41);
  a07=(a07+a12);
  if (res[0]!=0) res[0][16]=a07;
  a07=2.1800000000000000e-01;
  a07=(a07*a11);
  a37=(a37+a07);
  a37=(a37+a12);
  if (res[0]!=0) res[0][17]=a37;
  a37=1.2000000000000000e-01;
  a37=(a37*a42);
  a41=(a37+a41);
  a41=(a41+a12);
  if (res[0]!=0) res[0][18]=a41;
  a37=(a37+a07);
  a37=(a37+a12);
  if (res[0]!=0) res[0][19]=a37;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov2heavy_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov2heavy_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bluerov2heavy_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov2heavy_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2heavy_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2heavy_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2heavy_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2heavy_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2heavy_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
